### ISSUE TITLE
Two Factor Auth

### ISSUE THREAD

**Issue by andyjhall** [morph1904/TygerCaddy#113]
Would it be worth adding two factor authentication ?

**Comment by morph1904** [comment]
@andyjhall This one is a little tricky, are you thinking that the userbase for this would be the hobbyist or enterprise user?

**Comment by andyjhall** [comment]
Still hobbyist, I was purely thinking this might be a good idea as I was considering publishing the management UI out as a subdomain and thought this would give better security. If you can point me in the first direction of the authentication routine I’m happy to have a crack at this myself

**Comment by morph1904** [comment]
I am happy to include it, we are also currently looking at LDAP support so i would need to look into the best way of implementing both solutions with an option to choose. We are also looking at converting this into an API based app so may need to look at a design strategy for this.

**Comment by hank** [comment]
I currently do this with a BUNCH of my vhosts because I don't trust the security of the random webservers in the backend. This is especially concerning when considering something like a router, since their HTTP servers are constantly outdated and terrible. With JWT, I have to auth through Google first, and I have this all set up in Caddy now working great. I cannot really use Tyger until it has this feature unfortunately.

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
