### ISSUE TITLE
Add posibility to set Logins for Subdomains

### ISSUE THREAD

**Issue by Sundune** [morph1904/TygerCaddy#35]
Hey, are you planing to add a way to set logins for the routed subdomains?
Like a .htpasswd or similar.

**Comment by sparky8251** [comment]
Not all web servers support authentication (or are setup with it). In such cases it is common to use a reverse proxy to secure it.

I second that it would be nice to have this.

**Comment by morph1904** [comment]
There are a few ways that this could be implemented but this would need to be done very carefully due to the way caddy deals with this.
 
https://caddyserver.com/docs/basicauth
Uses plain text to store basic auth credentials and if not using HTTPS will be sent unencrypted. 

https://caddyserver.com/docs/http.login
Will be complicated to implement as JWT will need to be stored locally somewhere. 

This is possible but complicated and i would like to see it created but I feel that it may be a while before a secure working version is ready.

**Comment by andyjhall** [comment]
BasicAuth seems like it should be easy to implement, i assume i would edit the models.py inside /hosts? and then the generateCaddyfile routine? If you can give me some pointers im happy to quickly impliment it as two new fields on the update host form.

**Comment by morph1904** [comment]
@andyjhall 

Hi Andy, I have added a very simple implementation of basic auth in the API branch with this commit [#17736bd](https://github.com/morph1904/TygerCaddy/commit/17736bd00e83e1605e43cb1bedabff653175f1c0). Let me know if you are able to test it for us. 

morph1904

**Comment by andyjhall** [comment]
how am i best upgrading from master? tried adding -b inside the upgrade script but that broken everything

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
