### ISSUE TITLE
Hostname Prefix

### ISSUE THREAD

**Issue by andyjhall** [morph1904/TygerCaddy#97]
Not sure if i have something setup incorrectly, but it seems i am unable to browse to a proxied hostname unless i prefix the name with http:// or https://

If i do not include this i get the below error:

404 Site **** is not served on this interface

**Comment by morph1904** [comment]
Hi @andyjhall.

This is correct as caddy does support proxying different protocols. We can add a note to the form to highlight this. We have included this detail in the quick start. 

Is this ok ?

**Comment by andyjhall** [comment]
The caddy user guide however specifies that a host without the http or https prefix should listen on both, am i misunderstanding?

Extract from https://caddyserver.com/docs/http-caddyfile

:2015                    # Host: (any), Port: 2015
localhost                # Host: localhost; Port: 2015
localhost:8080           # Host: localhost; Port: 8080
example.com              # Host: example.com; Ports: 80->443
http://example.com       # Host: example.com; Port: 80
https://example.com      # Host: example.com; Ports: 80->443
http://example.com:1234  # Host: example.com; Port: 1234
https://example.com:80   # Error! HTTPS on port 80
*                        # Hosts: *; Port: 2015
*.example.com            # Hosts: *.example.com; Port: 443
*.*.example.com          # Hosts: *.*.example.com; Port: 2015
example.com/foo/         # Host: example.com; Ports: 80, 443; Path: /foo/
/foo/                    # Host: (any), Port: 2015, Path: /foo/

**Comment by morph1904** [comment]
Sorry Andy I misunderstood you. Can you sent me a copy of your caddyfile.conf that is not working? It is located /apps/TygerCaddy/TygerCaddy/data/caddyfile.conf

I am not aware of a method of passing through the certificate from your proxied server to caddy. You are able to specify them manually but this is not a feature that we have added yet. If you would like to see us do this in the next release please log a new issue.

**Comment by andyjhall** [comment]
media.example.com {
         root /
                 proxy / http://192.168.0.204 {
                 }
        tls off
 }

http://test.example.com {
         root /
                 proxy / http://192.168.0.204 {
                 }
        tls off
 }

https://nas.example.com {
         root /
                 proxy / 192.168.0.201:5001 {
                 }

 }

192.168.0.205:80 {

proxy / 192.168.0.205:9090 {
transparent
except /assets
}

root /apps/TygerCaddy/TygerCaddy
}
-----
As above the media.example.com isnt working however http://test.example.com is

**Comment by morph1904** [comment]
Hi @andyjhall 

I have spun up a new server, re-read some caddy docs and done some testing. As far as i can see, there is no issue with the caddyfile generation or with the configuration of TygerCaddy or Caddy itself. 

What I have worked out is, without SSL (tls off) in the host definition, Caddy does not recognise the domain without either http:// or :80 defined in the host. If you have TLS on however, this works fine without the http:// or port :80 defined as Caddy with automatically redirect to https://example.com:443.

I have not yet been able to work out if this is a bug or by design with Caddy. 

As far as I can see though, as this is not an issue with Caddy's config or with TygerCaddy, there is little I can do to mitigate the issue, the only thing I can suggest is that I add some code to automatically add "http://" to the host definition if TLS is off. I am cautious about doing this though as it may limit later applications for certain audiences. 

[Ref: https://caddyserver.com/docs/http-caddyfile](https://caddyserver.com/docs/http-caddyfile)

Site Addresses
The HTTP server uses site addresses for labels. Addresses are specified in the form  scheme://host:port/path, where all but one are optional.

The host portion is usually localhost or the domain name. The default port is 2015 (unless the site qualifies for automatic HTTPS, in which case it's changed to 443 for you). The scheme portion is another way to specify a port. Valid schemes are "http" or "https" which represent, respectively, ports 80 and 443. If both a scheme and port are specified, the port takes precedence. For example (this table assumes automatic HTTPS is applied where it qualifies):

[https://caddyserver.com/docs/tls](https://caddyserver.com/docs/tls)

tls
tls configures HTTPS connections. Since HTTPS is enabled automatically, this directive should only be used to deliberately override default settings. Use with care, if at all.

Caddy supports SNI (Server Name Indication), so you can serve multiple HTTPS sites from the same port on your machine. In addition, Caddy implements OCSP stapling for all qualifying certificates. Caddy also automatically rotates all TLS session ticket keys periodically.

The tls directive will ignore sites that are explicitly defined to be http:// or are on port 80. This allows you to use the tls directive in a server block that is shared with both HTTP and HTTPS sites.

**Comment by morph1904** [comment]
@andyjhall I have included a fix that will automatically add a HTTP:// prefix if one is not present and TLS is off. This will be included in the official Alpha 0.2 release soon.

**Comment by morph1904** [comment]
@andyjhall Alpha 0.2 is now officially released. Are you happy for me to close this issue?

**Comment by andyjhall** [comment]
Yes happy this works, thanks.
